Bugs: general fixes
loggingroads/onboarding pull request #55
Opened 2016-10-31 18:14 UTC by edbrett

- css style fixes for participate section (homepage)
- update data feed for community section (homepage)
- fix rendering polygons on front end for tasks and events single views
- update map component to also show pop up the above views
- Reimplement responsive mobile styles for all tables (from old React component)
- Fix the order of the switchers in the maps

Other: added snippet to give smooth scroll to anchor links site wide for improved Homepage experience.

2016-11-01 11:16 UTC, simaob requested changes
Hi Edward, most things are ticked, but there's a comment to address here and some others on Pivotal Tracker. Let me know if something is not clear! Happy to discuss, hopefully Wednesday I'll have more time than I did on Monday! =) Thanks!

2016-11-01 11:16 UTC, simaob commented on app/assets/javascripts/components/Map.js
> +              <a href="/campaigns/${layer.events ? layer.events[0].campaign_id : this.props.campaignId}">Campaign</a>
A task might belong to more than one event and/or campaigns, so I think we should maybe iterate over them and display a link to each. Probably worth checking with Juanca for ideas on how best to show it.

2016-11-02 10:16 UTC, edbrett commented on app/assets/javascripts/components/Map.js
> +              <a href="/campaigns/${layer.events ? layer.events[0].campaign_id : this.props.campaignId}">Campaign</a>
I have discussed with Juan Carlos and will try to find a design solution. With regards to responsive maps fitting to screen height, we have the use case for events that there is a header above the map therefore on mobile map fitting is not possible. I can approximate but not force map to fit to bottom of screen in all cases.

2016-11-02 12:26 UTC, edbrett commented
Updated

2016-11-02 12:35 UTC, simaob commented on app/assets/javascripts/components/Map.js
> +              <a href="/campaigns/${layer.events ? layer.events[0].campaign_id : this.props.campaignId}">Campaign</a>
That works for me! =) Thanks!

2016-11-02 12:36 UTC, simaob approved these changes

2016-11-02 12:37 UTC, merged